### ISSUE TITLE
Toggling theme in TopBar doesn't change theme colours

### ISSUE THREAD

**Issue by Caladan08** [svelteuidev/svelteui#237]
### Link to the page where something isn't quite right

https://www.svelteui.org/

### Exact quote of what is wrong

Clicking on the "Experimental Theme Toggle" button in the `TopBar` doesn't actually change any of the colours. I tried looking into why this was like this and I've not got anywhere so far.  In the `TopBar` component's `.svelte` file (`apps/docs/src/components/TopBar/TopBar.svelte`), clicking on the button does change the `$colorScheme` store but I'm not sure where `$colorScheme` is passed into the `SvelteUIProvider` to see where it goes wrong. 

### Are you willing to create pull request with the fix?

Yes

**Comment by BeeMargarida** [comment]
My bad, an issue when deploying the docs, should be fixed now

**Comment by Caladan08** [comment]
If you don't mind, could you tell how exactly is this theming implemented in the docs? I checked the `@svelte-docs/core` and it really didn't have anything regarding changing the theme colours on the click of a button. I was able to change the theme colours a little bit by changing the styles in `style.css` in the `themes` folder of the docs but nothing apart from that. I'm interested in improving the dark theme for the docs but I've not got anywhere so far because of this

**Comment by BeeMargarida** [comment]
Basically what you see in `Global.svelte` is added to the svelte-docs App.svelte before building the docs (it's a hack, but since the docs will be ported, it's something we live with for now). That includes the SvelteUIProvider that contains a dark/light theme switch logic. Most of the style of dark/light theme come from the components themselves. @Brisklemonade can give more details, since he was the one that set up all the docs 🙌 

I'm not sure it is a right investment to improve the dark theme for the docs since we have plans to port them to sveltekit

**Comment by Caladan08** [comment]
Yeah, I was wondering whether I should do this since I saw porting to SvelteKit on the repo's roadmap. But thanks anyway!

**Comment by Brisklemonade** [comment]
@BeeMargarida explained it pretty well, and since we are going to be porting I don't think it's worth the investment. But thank you for looking into it.
