### ISSUE TITLE
[Feature Request] Flex component

### ISSUE THREAD

**Issue by mazipan** [svelteuidev/svelteui#254]
### Usage example, including component, action, motion, or utility API

Mantine is releasing Flex component on [version 5.7.0](https://mantine.dev/changelog/5-7-0/#flex-component) as alternative for Group and Stack.

Docs: https://mantine.dev/core/flex/

### Possible implementation - describe how the feature can be implemented

Mantine implementation: https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Flex/Flex.tsx

### Do you want to contribute this feature and create a pull request

No

**Comment by Brisklemonade** [comment]
I'm not seeing why this would be needed considering group and stack exist.

**Comment by drewbitt** [comment]
@Brisklemonade At their simplest & defaults, Grid is a div element with flex and `flex-wrap`, `justify-content`, `align-items`, and `margin` set. Stack is a div with flex and `flex-direction`, `align-items`, `justify-content`, and `gap` set. Rather than setting numerous defaults that have to be removed to get a simple `<div display="flex">`, a Flex component is possible. Users from tools like Chakra are also accustomed to <Flex> elements. I often start design with a simple flex div and iterate from there. Why force so many defaults by requiring Group or Stack?
