### ISSUE TITLE
`Card` don't have gap between items

### ISSUE THREAD

**Issue by notramo** [svelteuidev/svelteui#397]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

`Card` component is missing vertical gap.
The documentation example looks correct in my browser:
![image](https://github.com/svelteuidev/svelteui/assets/26059643/1532fb4a-0753-4b68-97d1-1b9b09825b20)
but when copy-pasting the example code to a local project, it looks like this:
![image](https://github.com/svelteuidev/svelteui/assets/26059643/9a2b5cf3-d084-4478-8fd9-4ef368f89d94)

### In which browser(s) did the problem occur?

Firefox

### Steps To Reproduce

Copy-paste the example code in the documentation to a local project.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by BeeMargarida** [comment]
That's a case of simplification that we make on the docs so that the examples are not too verbose. The code used can be seen [here](https://github.com/svelteuidev/svelteui/blob/aa35158ca607cbb443c2879f4fc3cef050eb6384/packages/svelteui-demos/src/demos/core/Card/Card.demo.usage.svelte#L68).
We already have an issue to add a link to the demo code in the docs - https://github.com/svelteuidev/svelteui/issues/232
